### ISSUE TITLE
Update tekton task to Platform API 0.2

### ISSUE THREAD

**Issue by jromero** [buildpacks/tekton-integration#2]
Update tekton template to adhere to Platform API version 0.2.

### Additional Considerations
- We should use the sample builder and sample java app as inputs on the example to make it easier to use off-the-shelf while annotating what and how things should be configured. This is in relation to a conversation on [slack](https://buildpacks.slack.com/archives/C94UJCNV6/p1580150479034100) and https://github.com/tektoncd/catalog/issues/151.

#### AC1. Platform API verification
```gherkin
Given the tekton task is configured for Platform API version 0.2
When I provide a builder with lifecycle implementing to Platform API version 0.3
Then task should fail with error message:
`Lifecycle's Platform API version is 0.3 which is incompatible with Platform API version 0.2`
```

### Notes
- Template is housed: https://github.com/tektoncd/catalog/tree/master/buildpacks

Relates to:
- https://github.com/buildpacks/docs/issues/111

Blocked by: 
- https://github.com/buildpack/rfcs/pull/29

**Comment by natalieparellano** [comment]
### Acceptance steps:

* Setup a local k8s cluster
  * Docker > Preferences > Kubernetes > Enable Kubernetes > Apply & Restart
  * `kubectl config current-context` should be `docker-desktop`
* Run a local registry
  * `docker run --detach -p5000:5000 registry:2`
* Permit insecure registry:
  * Docker > Preferences > Docker Engine > add the line `"insecure-registries" : ["localhost:5000"]` > Apply & Restart
* Install tekton
  * kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
* Install buildpacks task
  * `kubectl apply -f ./buildpacks-v3.yaml`
* Apply taskrun
  * Edit the example under Usage in the README
  * output url will look like `<your external ip>:5000/some-output-image` (localhost might work too but we didn't verify that with Docker desktop - `minikube` requires external IP)
  * `kubectl apply -f <path to task run yaml>`
* See task succeed
* See output image written to registry
  * `docker pull localhost:5000/some-output-image`

To test persistent cache:

* Create a persistent volume pointing to local cache directory
  * `mkdir <some dir>`
  * ensure the directory is writable by the world: `chmod 777 <some dir>`
  * edit [pv-volume.yaml](https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/pods/storage/pv-volume.yaml) to have the correct host path
  * `kubectl apply -f <path to volume yaml>`
* Create a persistent volume claim
  * `kubectl apply -f https://k8s.io/examples/pods/storage/pv-claim.yaml`
* Update the taskrun
  * Uncomment the lines that pertain to caching
* Apply taskrun
  * `kubectl apply -f <path to task run yaml>`
* See task succeed
* See items in the cache directory

**Comment by dfreilich** [comment]
@natalieparellano Was this taken care of?

**Comment by natalieparellano** [comment]
Yep!
