### ISSUE TITLE
Add task/buildpacks label to tekton/catalog

### ISSUE THREAD

**Issue by jromero** [buildpacks/tekton-integration#3]
The goal of this is to provide a mechanism in which we can enable tooling (at least filtering) to better understand what issues created in tekton/catalog are associated with our team.

This initial proposal was made on slack: https://tektoncd.slack.com/archives/CK9JGKS20/p1580153383003200

> - jromero
Hi, seems like our team (buildpacks) has missed a good amount of issues reported in the catalog. In efforts to try to make it better going forward, are there any practices employed by other teams to maintain their designated catalog entry?
One thing I thought about was the idea of task/buildpacks label that we can then filter against and potentially automate/integrate into our processes.
> - vdemeester
@jromero that's sound like a good idea (the label)
can you open an issue (or better) a PR in plumbing ?
https://github.com/tektoncd/plumbing/tree/master/label_sync

**Comment by dfreilich** [comment]
An issue we've seen with this is that this depends on tekton folk to add the label, which they won't necessarily do. We should probably add something to our Community role ([doc](https://docs.google.com/document/d/1DfRf9WRPpAjb0twg4DNtSOKHEnlyxGiLeOZkGB5NH-E/edit) to look at tekton issues and add the task, if we want to utilize this label.
