### ISSUE TITLE
Improve support for build time env vars

### ISSUE THREAD

**Issue by jromero** [buildpacks/tekton-integration#5]
Although there is a current solution to providing env variables via the `/platform` directory interface. It may be better to provide an easier interface for the task. For example, pack-orb allows users to pass env variables delimited by semi-colons (;) as a parameter. We should be able to so something similar via the `prepare` step.

Related to https://github.com/buildpacks/tekton-integration/issues/4.

**Comment by benjaminhuo** [comment]
Looking forward to enhancement like this.
